#!/usr/bin/env python3
"""DEV ONLY. Build the self-teaching workers from the game's text dump.

    git clone https://github.com/CPokemon/swsh-text
    python3 dev/gen_teach.py path/to/swsh-text [lang ...]

Writes dev/teach/teach_<lang>.lua (default: en) = DICT + dev/teach/teacher.lua.
Languages: en de fr it es ko ja-hiragana ja-katakana ch-simplified ch-traditional
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEACH = os.path.join(ROOT, "dev", "teach")
UNSPACED = {"ja-hiragana", "ja-katakana", "ch-simplified", "ch-traditional"}


def own_script(lang, c):
    o = ord(c)
    if lang in UNSPACED:
        return True
    if lang == "ko":
        return o < 0x2E80 or 0xAC00 <= o <= 0xD7AF or 0x3130 <= o <= 0x318F
    return o < 0x2E80


def messages(dump, lang):
    seen = set()
    for part in ("story", "common"):
        with open(os.path.join(dump, part, lang + ".txt"), encoding="utf-8") as f:
            for line in f:
                line = line.rstrip("\n")
                if (not line or line.startswith("~~~") or line.startswith("Text File :")
                        or re.fullmatch(r"\[~ \d+\]", line)):
                    continue
                # Placeholders (names, numbers, page breaks) end a run of
                # literal text: nothing on screen can be matched across them.
                for seg in re.split(r"\[VAR [^\]]*\]", line):
                    seg = seg.strip()
                    if seg and seg not in seen:
                        seen.add(seg)
                        yield seg


def main():
    dump, langs = sys.argv[1], sys.argv[2:] or ["en"]
    with open(os.path.join(TEACH, "teacher.lua"), encoding="utf-8") as f:
        body = f.read()
    for lang in langs:
        text = "\n".join(messages(dump, lang))
        eq = "=" * 1
        while ("]" + eq + "]") in text:
            eq += "="
        # Every distinct character the language's text uses: the "out of how
        # many" for the known-glyphs count.
        # Untranslated strings (Japanese default names, credits) are in every
        # dump; they aren't letters that language's boxes need, so the count
        # only takes characters from the language's own script.
        charset = "".join(sorted(c for c in set(text) - {" ", "\n", "\u3000"}
                                 if own_script(lang, c)))
        out = os.path.join(TEACH, f"teach_{lang}.lua")
        with open(out, "w", encoding="utf-8") as f:
            f.write(f"-- GENERATED by dev/gen_teach.py from CPokemon/swsh-text ({lang}). DEV ONLY.\n")
            f.write(f"SPACED = {'false' if lang in UNSPACED else 'true'}\n")
            f.write(f"CHARSET = [{eq}[\n{charset}]{eq}]\n")
            f.write(f"DICT = [{eq}[\n{text}\n]{eq}]\n\n")
            f.write(body)
        print(f"{out}: {os.path.getsize(out) // 1024} KB")


if __name__ == "__main__":
    main()
