#!/usr/bin/env python3
"""Build lua/autorun/05_atlas.lua from labelled screenshots, and check it.

Runs the addon's own workers/reader.lua (through lupa, `pip install lupa`), so
the fingerprints in the atlas are made by exactly the code that will match
against them in the engine.

    python3 dev/gen_atlas.py          # rebuild the atlas from dev/samples
    python3 dev/gen_atlas.py --check  # read every sample with the atlas

Samples are 1920x1080 screenshots listed in dev/samples/truth.txt as
"<file>\t<line 1>|<line 2>". The geometry below must match SWSH.BOX in
lua/autorun/10_mod.lua.
"""
import os, sys
import numpy as np
from PIL import Image
from lupa import lua54

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SAMPLES = os.path.join(ROOT, "dev", "samples")
OUT = os.path.join(ROOT, "lua", "autorun", "05_atlas.lua")

X0, X1 = 400, 1492                      # text columns, 1080p
LINES = [(889, 956), (967, 1034)]       # [top, bottom) rows of each line
PER_CHAR = 3                            # samples kept per character


def luma(path):
    """Limited-range BT.709 luma, which is what an HD capture's Y plane holds."""
    im = np.asarray(Image.open(path).convert("RGB")).astype(float)
    y = 16 + 0.1826 * im[..., 0] + 0.6142 * im[..., 1] + 0.0620 * im[..., 2]
    return np.clip(y, 0, 255).astype(np.uint8)


def runtime():
    L = lua54.LuaRuntime(encoding=None)
    with open(os.path.join(ROOT, "workers", "reader.lua"), "rb") as f:
        L.execute(f.read())
    return L


def job(L, Y):
    lines = [L.table(*[Y[y, X0:X1].tobytes() for y in range(a, b)]) for a, b in LINES]
    return L.table_from({b"seq": 1, b"w": X1 - X0, b"lines": L.table(*lines), b"learn": True})


def atlas_table(L, entries):
    return L.table(*[L.table_from({b"ch": c.encode(), b"w": w, b"t": t, b"b": b,
                                   b"f": L.table(*f)}) for c, w, t, b, f in entries])


def read(L, path):
    r = L.globals().onJob(job(L, luma(path)))
    out = []
    for i in (1, 2):
        ln = r[b"lines"][i]
        gl = [(g[b"w"], g[b"t"], g[b"b"], list(g[b"f"].values()))
              for g in ln[b"glyphs"].values()]
        out.append((ln[b"text"].decode("utf-8", "replace"), gl))
    return out


def samples():
    with open(os.path.join(SAMPLES, "truth.txt"), encoding="utf-8") as f:
        for line in f:
            if line.strip():
                name, text = line.rstrip("\n").split("\t")
                yield os.path.join(SAMPLES, name), text.split("|")


def build():
    entries, count = [], {}
    for path, truth in samples():
        for (text, glyphs), want in zip(read(runtime(), path), truth):
            chars = [c for c in want if c != " "]
            if len(chars) != len(glyphs):
                print(f"skip {os.path.basename(path)} {want!r}: "
                      f"{len(glyphs)} glyphs for {len(chars)} characters")
                continue
            for c, (w, t, b, f) in zip(chars, glyphs):
                if count.get(c, 0) < PER_CHAR:
                    count[c] = count.get(c, 0) + 1
                    entries.append((c, w, t, b, f))
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("-- GENERATED by dev/gen_atlas.py from dev/samples -- do not edit.\n")
        f.write("-- Glyph fingerprints of the Sword/Shield dialogue font; see\n")
        f.write("-- workers/reader.lua for what the numbers mean.\n")
        f.write("SWSH = SWSH or {}\nSWSH.atlas = {\n")
        for c, w, t, b, fv in entries:
            q = c.replace("\\", "\\\\").replace('"', '\\"')
            f.write('    { ch = "%s", w = %.4f, t = %.4f, b = %.4f, f = { %s } },\n'
                    % (q, w, t, b, ", ".join("%.3g" % v for v in fv)))
        f.write("}\n")
    print(f"wrote {len(entries)} glyphs, {len(count)} characters: "
          + "".join(sorted(count)))
    return entries


def check(entries):
    for path, truth in samples():
        L = runtime()
        L.globals().ATLAS = atlas_table(L, entries)
        for (text, _), want in zip(read(L, path), truth):
            print(("ok  " if text == want else "BAD ") + text)


if __name__ == "__main__":
    e = build()
    if "--check" in sys.argv:
        check(e)
